# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'Instalar Newman'
  inputs:
    script: 'sudo npm install -g newman'

- task: CmdLine@2
  displayName: 'Instalar Newman-reporter-html'
  inputs:
    script: 'sudo npm install -g newman-reporter-html'

- task: CmdLine@2
  displayName: 'Instalar reporter'
  inputs:
    script: 'sudo npm install -g reporter'
    
    

- task: NewmanPostman@4
  inputs:
    collectionSourceType: 'file'
    Contents: 'PayrollLiquidator.postman_collection.json'
    environmentSourceType: 'none'
    dataFile: 'Nominacsv1.csv'
    numberOfIterations: 
    reporters: 'html, htmlextra'
    htmlExtraDarkTheme: true
    htmlExtraLogs: true
    htmlExtraTestPaging: true


