# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'Install Newman'
  inputs:
    script: 'sudo npm install -g newman'
- task: NewmanPostman@4
  inputs:
    collectionSourceType: 'file'
    collectionFileSource: '$(System.DefaultWorkingDirectory)/Postman/PayrollLiquidator_V2.postman_collection.json'
    dataFile: '$(System.DefaultWorkingDirectory)/Postman/Nominacsv1_V2.csv'
    numberOfIterations: 
    sslInsecure: true
    reporters: 'junit'
    environmentSourceType: 'None'


  
