# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: CmdLine@2
  displayName: 'Install Newman'
  inputs:
    script: 'sudo npm install -g newman'   
- task: CmdLine@2
  displayName: 'Install Newman-Reporter-htmlextra'
  inputs:
    script: 'sudo npm install -g newman-reporter-htmlextra'   
    
- task: CmdLine@2
  displayName: 'PayrollLiquidator Test Execution'
  continueOnError: true
  inputs:
    script: 'newman run PayrollLiquidator_V2.postman_collection.json -d Nominacsv1_V2.csv --insecure -r cli,htmlextra --reporter-htmlextra-export ./results/index.html'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Postman'
- task: UploadPostmanHtmlReport@1
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)/Postman/results'
    tabName: 'Postman Payroll'



    